### ISSUE TITLE
https://gofile.io/d/ziR7AG is unuseful

### ISSUE THREAD

**Issue by 528288** [MineCreeper86/SuishenmaProtest#3]

**Comment by MineCreeper86** [comment]
I've already noticed this issue, this link is provided by who sold these information, maybe it has been manually deleted. However, I have a backup in my storage, if you need that, I'll try to upload it somewhere.

**Comment by 528288** [comment]
thank you very much，if it is possible,send it to my gmail qianduowei123@gmail.com

**Comment by Sunzheng-Hub** [comment]
Please also send me a copy, thank you sunzheng1105@gmail.com

**Comment by MineCreeper86** [comment]
Ok, but I am a little curious about what are you going to do through these data. We can just chat through gmail.

**Comment by MineCreeper86** [comment]
I'll probably send it on tomorrow morning (utc+8)

**Comment by Sunzheng-Hub** [comment]
> Ok, but I am a little curious about what are you going to do through these data. We can just chat through gmail.

Nothing, I was just curious if myself was in the sample data.

**Comment by MineCreeper86** [comment]
> > Ok, but I am a little curious about what are you going to do through these data. We can just chat through gmail.
> 
> Nothing, I was just curious if myself was in the sample data.

Haha, I understand what you mean.

**Comment by EvanNotFound** [comment]
I've made a new link. Please go to [here](https://mega.nz/file/BTNxhZbS#gfS9lEJsmuXc9dmSmiZ0bxgBplGa__OCiBE9MuzS-N8) to download the file

**Comment by MineCreeper86** [comment]
> I've made a new link. Please go to [here](https://mega.nz/file/BTNxhZbS#gfS9lEJsmuXc9dmSmiZ0bxgBplGa__OCiBE9MuzS-N8) to download the file

My kind-hearted friend helped me upload this
